# Generated by Django 4.2.4 on 2023-08-06 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(50, 'the field must contain at least 50 characters')]),
        ),
    ]
