# Generated by Django 4.2.4 on 2023-08-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
